### ISSUE TITLE
[BUG]  Black line appearance on profile page 

### ISSUE THREAD

**Issue by avibiradar100** [avibiradar100/SaahityaWce#3]
### **Description**

On the profile page black line is appearing between the profile page and nav bar 
### Screenshots
<img width="974" alt="Screenshot 2023-10-25 at 3 26 15 PM" src="https://github.com/avibiradar100/SaahityaWce/assets/74947684/7e72a913-d619-4e58-9004-c7e612e89641">

### Are you willing to work on this issue ?

**Comment by vyb2014962** [comment]
hi @avibiradar100  can i take this?

**Comment by avibiradar100** [comment]
> hi @avibiradar100 can i take this?

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/avibiradar100/SaahityaWce/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by AlimKhan76** [comment]
@avibiradar100  is this issue still open and can I have the detail of the expected output?

**Comment by avibiradar100** [comment]
> @avibiradar100 is this issue still open and can I have the detail of the expected output?

@AlimKhan76  it should be like this
<img width="1606" alt="Screenshot 2023-10-28 at 10 34 02 AM" src="https://github.com/avibiradar100/SaahityaWce/assets/74947684/4551dd89-f276-4fb6-a9af-decbd2d73ecc">

**Comment by AlimKhan76** [comment]
@avibiradar100  Can u assign the issue to me?

**Comment by avibiradar100** [comment]
issue resolved
