### ISSUE TITLE
[Bug]  Add products to liked list

### ISSUE THREAD

**Issue by avibiradar100** [avibiradar100/SaahityaWce#4]
### **Description**

- checkout any product
-  click on `Add to liked list` button and check the liked list count
-  it's not updating the liked items count

### Screenshots

https://github.com/avibiradar100/SaahityaWce/assets/74947684/7c65e48f-5070-4488-aac4-2f629554fff7

### Are you willing to work on this issue ?

**Comment by AlimKhan76** [comment]
@avibiradar100  Can u assign this to me?

**Comment by avibiradar100** [comment]
sure @AlimKhan76 , thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/avibiradar100/SaahityaWce/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck !

**Comment by AlimKhan76** [comment]
Hey @avibiradar100  can u tell me how to start the server, it is opening on an undefined port .

**Comment by avibiradar100** [comment]
check steps https://github.com/avibiradar100/SaahityaWce#readme here

**Comment by AlimKhan76** [comment]
![Screenshot (2)](https://github.com/avibiradar100/SaahityaWce/assets/120938653/ad476564-8362-4f81-9af4-cf8aef32fac9)
@avibiradar100 
It is giving this error and I cannot connect to the database, is there a developmental database  or should i make my own

Also there is no config.env file

**Comment by avibiradar100** [comment]
make one config.env and add db uri there

**Comment by AlimKhan76** [comment]
Hey @avibiradar100 , I was unable to recreate the bug in my local copy. However, I have found the source of the bug, the url that is called on the click of the button is different from the one present in the repo.
 The working url is 
https://saahitya-wce.onrender.com/api/v1/product/${id} and this is present in the repo .
and the url that the actual website is calling is 
https://saahitya-wce.onrender.com/product/undefined/api/v1/product/${id}
There is a undefined in between product and api, that is the problem .

I have also attached a video for better understanding 

https://github.com/avibiradar100/SaahityaWce/assets/120938653/acdc01e6-4a6e-44ab-851d-f63c5913eba2

**Comment by avibiradar100** [comment]
yes good catch @AlimKhan76 , kudos to you..
do you have any solution for this

**Comment by AlimKhan76** [comment]
@avibiradar100 is the code hosted on render and the one present in the repository the same, because I haven't made any changes to the cartAction code and it is working and the items are getting stored in local Storage

If the code is not the same then I suggest you to look at 
SaahityaWce\frontend\src\actions\cartAction.js

and the link in the action addItemstoCart should be https://saahitya-wce.onrender.com/api/v1/product/${id}

I believe the url that is present in the hosted code which is being called in the addItemstoCart is  api/v1/product/${id}

![image](https://github.com/avibiradar100/SaahityaWce/assets/120938653/5a0a9e69-8c5c-49d6-a782-077b6d8708b8)

**Comment by avibiradar100** [comment]
@AlimKhan76 it's a same code as main branch is considered for deployment

**Comment by AlimKhan76** [comment]
@avibiradar100 This bug is still in the website, can you please reopen it and assign it to me.
I would like to solve it .

**Comment by avibiradar100** [comment]
Hey @AlimKhan76  no need it's not reflected in the prod env

**Comment by AlimKhan76** [comment]
@avibiradar100 is the bug fixed?
Cuz, in my pc, it is still not fixed on your website.
