### ISSUE TITLE
Add some hover effects in the navbar

### ISSUE THREAD

**Issue by harshsbhandari** [avibiradar100/SaahityaWce#6]
Add scaling effect on hovering the in the navbar @avibiradar100 I can fix that. Please assign it to me.
![Screenshot (165)](https://github.com/avibiradar100/SaahityaWce/assets/73375087/ce3f7bc3-6b1c-4a6e-8e86-69ba9a08180b)

**Comment by avibiradar100** [comment]
Definitely @harshsbhandari , thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/avibiradar100/SaahityaWce/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
